language: node_js
node_js:
- '0.11'
env:
  global:
    - secure: Swir0YoWBhWiIiLeAHwdM/BGSgh3CK2Be3MGUeLHBREFvJagCZj2csY3tleoW8ZAbbBAKY5Oce7XTgJOEfRzEAM8GRTNE+X8YLKjbYHpnKJyuejDjZG6aUP1+0A08clQimI+g98YH02mUaoZNorsJcW08aXYjztxKB/xRbFiKb0=
    - secure: ABDFaRrvSGZUMpA1fL8Lp1d4MMO5G2syWl7JT3E4rfyvIIYz6pY4UWArFkQogIBoa5lzGfM20t7jO7twHQbbHbbwAyhYEP0njXNPYczWH6SIiQMZ2bIcBEBdK3arVuyfkUxj4urtopiuCcGPLssPdPuay8P0wQiYoo/ZMLBYXFM=
